FROM docker.io/library/caddy:2-builder AS builder
RUN xcaddy build \
    --with github.com/caddy-dns/infomaniak \
    --with github.com/caddy-dns/ovh

FROM docker.io/library/caddy:2
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY Caddyfile /etc/caddy/Caddyfile
EXPOSE 80 443 2019
ENTRYPOINT ["caddy", "run", "--config", "/etc/caddy/Caddyfile"] 